print("# 1번문제")
print("Hello World")
print("# 2번문제")
print("Mary's cosmetics")
print("# 3번문제")
print('신씨가 소리질렀다. "도둑이야".')
print("# 4번문제")
print('"C:\Windows"')
print("# 5번문제")
print("안녕하세요.\n만나서\t\t반갑습니다.")
print("# 6번문제")
print("오늘은", "일요일")
print("# 7번문제")
print("naver", "kakao", "sk", "samsung", sep=";")
print("# 8번문제")
print("naver", "kakao", "sk", "samsung", sep="/")
print("# 9번문제")
print("first", end=" ");print("second")
print("# 10번문제")
print(5/3)